version: '{build}'
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: artifacts\**\*.*
environment:
  FeedzApiKey:
    secure: t1uaTrTw6lryUs3SLX/9TXZmDAgq/0Yy8R7svoeWP5AfQU1OgiyLwJS6cckJpqu8
  NuGetApiKey:
    secure: 2dAM0FOgXaVV9BAp+2wO4k+hJuQV6RovrQBYNGuIAYASfvN/GwoHlQ6MRc5MIVk5
  

